openapi: 3.0.0
info:
  title: User Authentication API
  description: API for user authentication and management.
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Local server

paths:
  /login:
    post:
      summary: User login
      description: Authenticates a user and returns a JWT token in a cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: P@ssw0rd
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
        '400':
          description: Bad request, missing email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email and password are required
        '401':
          description: Unauthorized, invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid credentials
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
      security:
        - cookieAuth: []
components:
  securitySchemes:
    cookieAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: cookie
      name: token
