openapi: 3.0.0
info:
  title: Logout Service API
  description: API for logging out a user
  version: 1.0.0
paths:
  /logout:
    post:
      summary: Log out a user
      description: Logs out a user by clearing the JWT token from the cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: <JWT token>
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout successful
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
