openapi: 3.0.0
info:
  title: Reservation Service API
  description: API documentation for the Reservation Service which logs RabbitMQ messages.
  version: 1.0.0
servers:
  - url: http://localhost:3018
    description: Local server
paths:
  /api-docs:
    get:
      summary: API Documentation
      description: Retrieves the API documentation for the Reservation Service.
      responses:
        '200':
          description: API documentation retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Swagger documentation for the Reservation Service"
components:
  schemas:
    Message:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        queue:
          type: string
        messageContent:
          type: string
      example:
        timestamp: "2024-07-21T14:48:00.000Z"
        queue: "reservation_created"
        messageContent: "Sample message content"
