openapi: 3.0.0
info:
  title: List Availability Service
  version: 1.0.0
  description: API for listing availability in the system
paths:
  /availability:
    get:
      summary: List all availability
      responses:
        '200':
          description: A list of availability
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    start_date:
                      type: string
                      format: date
                      example: "2024-07-21"
                    end_date:
                      type: string
                      format: date
                      example: "2024-07-22"
                    spots:
                      type: integer
                      example: 10
                    cost:
                      type: number
                      format: float
                      example: 50.00
        '500':
          description: Server error
